CREATE TABLE llx_type_marking (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(30) NOT NULL,
  detail text NOT NULL,
  mark integer NOT NULL,
  fixed_date date NULL,
  sex varchar(2) DEFAULT '-1' NOT NULL,
  day_def varchar(13) DEFAULT '0,1,2,3,4,5,6',
  primary_entry datetime NOT NULL,
  primary_exit datetime NOT NULL,
  secundary_entry datetime NOT NULL,
  secundary_exit datetime DEFAULT NULL,
  third_entry datetime DEFAULT NULL,
  third_exit datetime DEFAULT NULL,
  fourth_entry datetime DEFAULT NULL,
  fourth_exit datetime DEFAULT NULL,
  fifth_entry datetime DEFAULT NULL,
  fifth_exit datetime DEFAULT NULL,
  sixth_entry datetime DEFAULT NULL,
  sixth_exit datetime DEFAULT NULL,
  additional_time tinyint DEFAULT 0 NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  date_create date NOT NULL,
  tms timestamp,
  statut tinyint NOT NULL
) ENGINE=InnoDB;
