CREATE TABLE llx_licences (
  rowid interger AUTO_INCREMENT PRIMARY KEY,
  entity interger NOT NULL,
  ref varchar(30) COLLATE utf8_bin NOT NULL,
  fk_member interger NOT NULL,
  date_ini datetime NOT NULL,
  date_fin datetime NOT NULL,
  date_ini_ejec datetime NULL,
  date_fin_ejec datetime NULL,
  type_licence varchar(30) NOT NULL,
  detail text NOT NULL,
  halfday integer DEFAULT '0' NULL,
  halfday_ejec integer DEFAULT '0' NULL,
  date_create date NOT NULL,
  fk_user_create interger NOT NULL,
  fk_user_mod interger NOT NULL,
  fk_user_aprob interger DEFAULT NULL,
  fk_user_rev integer DEFAULT NULL,
  fk_user_reg interger DEFAULT NULL,
  datem date DEFAULT NULL,
  datea datetime DEFAULT NULL,
  dater datetime DEFAULT NULL,
  datev datetime DEFAULT NULL,
  tms timestamp NOT NULL,
  statut tinyint NOT NULL
) ENGINE=InnoDB;