
CREATE TABLE llx_assets_low (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_asset integer NOT NULL,
  fk_father integer DEFAULT '0',
  fk_facture_fourn integer DEFAULT '0',
  fk_facture integer DEFAULT '0',
  type_group varchar(30) NOT NULL,
  type_patrim varchar(30) NOT NULL,
  ref varchar(30) NOT NULL,
  ref_ext varchar(50) DEFAULT NULL,
  item_asset integer NOT NULL,
  date_adq date NOT NULL,
  date_day tinyint(4) NOT NULL,
  date_month tinyint(4) NOT NULL,
  date_year mediumint(9) NOT NULL,
  date_active date DEFAULT NULL,
  date_reval date DEFAULT NULL,
  useful_life_residual integer DEFAULT NULL,
  quant double NOT NULL,
  coste double(24,5) DEFAULT '0.00000',
  coste_residual double(24,5) DEFAULT '0.00000',
  coste_reval double(24,5) DEFAULT NULL,
  coste_residual_reval double(24,5) DEFAULT NULL,
  useful_life_reval double DEFAULT NULL,
  dep_acum double DEFAULT '0',
  fk_low integer DEFAULT NULL,
  date_baja date DEFAULT NULL,
  baja_day tinyint DEFAULT NULL,
  baja_month tinyint DEFAULT NULL,
  baja_year tinyint DEFAULT NULL,
  baja_resolution varchar(16) NULL,
  baja_objservation text NULL,
  baja_motive varchar(120) NULL,
  baja_amount_act DOUBLE(24,5) NULL,
  baja_amount_depgestion DOUBLE(24,5) NULL,
  amount_sale double(24,5) DEFAULT NULL,
  descrip varchar(250) NOT NULL,
  number_plaque varchar(30) DEFAULT NULL,
  trademark varchar(150) DEFAULT NULL,
  model varchar(150) DEFAULT NULL,
  anio smallint(6) DEFAULT NULL,
  fk_asset_sup integer DEFAULT '0',
  fk_location integer DEFAULT '0',
  code_bar varchar(20) DEFAULT NULL,
  fk_method_dep integer DEFAULT NULL,
  type_property varchar(4) DEFAULT NULL,
  code_bim varchar(50) DEFAULT NULL,
  fk_product integer DEFAULT NULL,
  useful_life double DEFAULT NULL,
  percent double DEFAULT NULL,
  account_accounting varchar(30) DEFAULT NULL,
  fk_unit integer DEFAULT NULL,
  model_pdf varchar(50) DEFAULT NULL,
  coste_unit_use double DEFAULT '0',
  fk_unit_use integer DEFAULT '0',
  codcont integer DEFAULT NULL,
  codaux integer DEFAULT NULL,
  orgfin varchar(3) DEFAULT NULL,
  cod_rube varchar(15) DEFAULT NULL,
  fk_departament integer DEFAULT NULL,
  fk_resp integer DEFAULT NULL,
  departament_name varchar(200) DEFAULT NULL,
  resp_name varchar(150) DEFAULT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  date_create date NOT NULL,
  date_mod date NOT NULL,
  mark varchar(5) DEFAULT ' ',
  been varchar(30) DEFAULT '1',
  tms timestamp NOT NULL,
  fk_asset_mov integer DEFAULT NULL,
  status_reval tinyint(4) DEFAULT NULL,
  statut tinyint(4) NOT NULL
) ENGINE=InnoDB;