CREATE TABLE llx_assets_mov (
  rowid integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  fk_asset integer NOT NULL,
  ref varchar(6) NOT NULL,
  type_group varchar(30) NOT NULL,
  date_ini date NOT NULL,
  date_end date NOT NULL,
  date_ini_day tinyint NULL,
  date_ini_month tinyint NULL,
  date_ini_year mediumint NULL,
  date_mig_day tinyint NULL,
  date_mig_month tinyint NULL,
  date_mig_year mediumint NULL,
  date_mig date NULL,
  factor_update double NOT NULL,
  time_consumed double NOT NULL,
  tcini double(24,10) NOT NULL,
  tcend double(24,10) NOT NULL,
  month_depr double(24,5) NOT NULL,
  date_adq date NULL,
  useful_life double NULL,
  coste double(24,5) NOT NULL,
  coste_mig double(24,5) DEFAULT '0' NULL,
  coste_residual double(24,5) NOT NULL,
  amount_base double(24,5) DEFAULT '0' NOT NULL,
  amount_update double(24,5) NOT NULL,
  amount_depr double(24,5) NOT NULL,
  amount_depr_acum double(24,5) NOT NULL,
  amount_depr_acum_update double(24,5) NOT NULL,
  amount_balance double(24,5) NOT NULL,
  amount_balance_depr double(24,5) NOT NULL,
  amount_sale double(24,5) NULL,
  movement_type varchar(30) NOT NULL,
  doc_reval varchar(30) NULL,
  detail text NULL,
  date_reval_day tinyint NULL,
  date_reval_month tinyint NULL,
  date_reval_year mediumint NULL,
  date_reval date NULL,
  fk_contab_seat integer NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  dateu date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL
) ENGINE=InnoDB;