CREATE TABLE llx_assets_assignment (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(30) NOT NULL,
  fk_user integer NOT NULL,
  fk_projet integer NOT NULL,
  fk_projet_from integer DEFAULT '0' NULL,
  fk_user_from integer DEFAULT '0' NULL,
  fk_user_to integer DEFAULT '0' NULL,
  fk_property integer NOT NULL,
  fk_location integer NOT NULL,
  detail text,
  date_assignment date NOT NULL,
  type_assignment varchar(1) NOT NULL,
  date_create date NOT NULL,
  date_mod date NOT NULL,
  mark varchar(5) DEFAULT ' ' NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  fk_user_approved integer DEFAULT '0' NULL,
  date_approved date NULL,
  model_pdf varchar(50) NULL,
  origin varchar(50) NULL,
  originid integer NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL
) ENGINE=InnoDB;
