CREATE TABLE llx_assets (
rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  fk_father integer DEFAULT '0' NULL,
  fk_facture_fourn integer DEFAULT '0' NULL,
  fk_facture integer DEFAULT '0' NULL,
  type_group varchar(30) NOT NULL,
  type_patrim varchar(30) NOT NULL,
  ref varchar(30) NOT NULL,
  ref_ext varchar(50) NULL,
  item_asset integer NOT NULL,
  date_adq date NOT NULL,
  date_day tinyint NULL,
  date_month tinyint NULL,
  date_year mediumint NULL,
  date_active date DEFAULT NULL,
  date_reval date NULL,
  useful_life_residual integer NULL,
  quant double NOT NULL,
  coste double(24,5) DEFAULT '0' NULL,
  coste_residual double(24,5) DEFAULT '0' NULL,
  coste_reval double(24,5) NULL,
  coste_residual_reval double(24,5) NULL,
  useful_life_reval double NULL,
  dep_acum double(24,5) DEFAULT '0' NULL,
  fk_low integer DEFAULT NULL,
  date_baja date DEFAULT NULL,
  baja_day tinyint DEFAULT NULL,
  baja_month tinyint DEFAULT NULL,
  baja_year tinyint DEFAULT NULL,
  baja_resolution varchar(16) NULL,
  baja_objservation text NULL,
  baja_motive varchar(120) NULL,
  baja_amount_act DOUBLE(24,5) NULL,
  baja_amount_depgestion DOUBLE(24,5) NULL,
  amount_sale double(24,5) DEFAULT NULL,
  descrip varchar(250) NOT NULL,
  number_plaque varchar(30) DEFAULT NULL,
  trademark varchar(150) NULL,
  model varchar(150) NULL,
  anio smallint NULL,
  fk_asset_sup integer DEFAULT '0' NULL,
  fk_location integer DEFAULT '0' NULL,
  code_bar varchar(20) DEFAULT NULL,
  fk_method_dep integer DEFAULT NULL,
  type_property varchar(4) DEFAULT NULL,
  code_bim varchar(50) DEFAULT NULL,
  fk_product integer DEFAULT NULL,
  useful_life double DEFAULT NULL,
  percent double NULL,
  account_accounting varchar(30) NULL,
  fk_unit integer DEFAULT NULL,
  model_pdf varchar(50) NULL,
  coste_unit_use double DEFAULT '0' NULL,
  fk_unit_use integer DEFAULT '0' NULL,
  codcont integer DEFAULT '0' NULL,
  codaux integer DEFAULT '0' NULL,
  orgfin varchar(3) DEFAULT NULL,
  cod_rube varchar(15) DEFAULT NULL,
  fk_departament integer DEFAULT NULL,
  fk_resp integer DEFAULT NULL,
  departament_name varchar(200) NULL,
  resp_name varchar(150) NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  date_create date NOT NULL,
  date_mod date NOT NULL,
  mark varchar(5) DEFAULT ' ' NULL,
  been tinyint DEFAULT '1' NULL,
  tms timestamp NOT NULL,
  fk_asset_mov integer NULL,
  status_reval tinyint DEFAULT NULL,
  statut tinyint NOT NULL
) ENGINE=InnoDB;