
CREATE TABLE llx_periodicity (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(30) NOT NULL,
  label varchar(255) NOT NULL,
  date_ini date NOT NULL,
  date_fin date NOT NULL,
  all_day tinyint NOT NULL DEFAULT '0',
  to_repeat integer DEFAULT NULL,
  condition_repeat text,
  type_repeat varchar(30) DEFAULT NULL,
  select_repeat text,
  end_repeat text,
  number_repeat integer DEFAULT NULL,
  count_repeat integer DEFAULT NULL,
  subsidiaries text,
  notification text,
  validation_notification text,
  as_notify text,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  fk_user_val integer DEFAULT NULL,
  fk_user_app integer DEFAULT NULL,
  active tinyint NOT NULL DEFAULT '0',
  datec date NOT NULL,
  datem date NOT NULL,
  datev integer DEFAULT NULL,
  datea integer DEFAULT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL
) ENGINE=InnoDB;