CREATE TABLE llx_bank_status (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_bank integer NOT NULL,
  fk_user integer NOT NULL,
  fk_subsidiary integer NULL,
  fk_bank_historial integer DEFAULT '0' NULL ,
  date_register datetime NOT NULL,
  date_close datetime NULL,
  exchange double(24,2) DEFAULT 0 NULL,
  previus_balance double(24,2) DEFAULT 0 NULL,
  amount double(24,2) NOT NULL,
  text_amount text NULL,
  amount_open double (24,2) DEFAULT '0' NULL,
  text_amount_open TEXT NULL,
  amount_balance double(24,2) DEFAULT '0' NULL,
  amount_income double(24,2) DEFAULT '0' NULL,
  amount_input double(24,2) DEFAULT '0' NULL,
  amount_sale double(24,2) DEFAULT '0' NULL,
  amount_null double(24,2) DEFAULT '0' NULL,
  amount_advance double(24,2) DEFAULT '0' NULL,
  amount_transf_input double(24,2) DEFAULT '0' NULL,
  amount_transf_output double(24,2) DEFAULT '0' NULL,
  amount_spending double(24,2) DEFAULT '0' NULL,
  amount_expense double(24,2) DEFAULT '0' NULL,
  amount_close double(24,2) DEFAULT '0' NULL,
  missing_money double(18,2) DEFAULT '0' NULL,
  leftover_money double(18,2) DEFAULT '0' NULL,
  amount_exchange double(18,2) DEFAULT '0' NULL,
  invoice_annulled double(18,2) DEFAULT '0' NULL,
  text_exchange text NULL,
  text_close text NULL,
  detail varchar(150) COLLATE utf8_bin NULL,
  var_detail text NULL,
  typebank tinyint DEFAULT '0' NOT NULL,
  model_pdf varchar(50) NULL,
  fk_user_create integer NOT NULL,
  fk_user_close integer NULL,
  fk_user_mod integer NOT NULL,
  date_create date NOT NULL,
  date_mod date NOT NULL,
  tms timestamp NOT NULL,
  statut tinyint NOT NULL
) ENGINE=InnoDB;
