ALTER TABLE llx_bank_status ADD UNIQUE KEY uk_unique (fk_bank,date_register,statut);
ALTER TABLE llx_bank_status ADD model_pdf VARCHAR(50) NULL AFTER var_detail;
ALTER TABLE llx_bank_status ADD fk_subsidiary INTEGER NULL AFTER fk_user;
ALTER TABLE llx_bank_status ADD missing_money DOUBLE(18,2) NULL DEFAULT '0' AFTER amount_close;
ALTER TABLE llx_bank_status ADD leftover_money DOUBLE(18,2) NULL DEFAULT '0' AFTER missing_money;
ALTER TABLE llx_bank_status ADD amount_exchange DOUBLE(18,2) NULL DEFAULT '0' AFTER leftover_money;
ALTER TABLE llx_bank_status ADD invoice_annulled DOUBLE(18,2) NULL DEFAULT '0' AFTER amount_exchange;
ALTER TABLE llx_bank_status ADD text_exchange TEXT NULL AFTER invoice_annulled;
ALTER TABLE llx_bank_status ADD text_close TEXT NULL AFTER text_exchange;
ALTER TABLE llx_bank_status ADD text_amount TEXT NULL AFTER amount;
ALTER TABLE llx_bank_status ADD amount_open DOUBLE(18,2) NULL DEFAULT '0' AFTER text_amount;
ALTER TABLE llx_bank_status ADD text_amount_open TEXT NULL AFTER amount_open;
ALTER TABLE llx_bank_status ADD typecash TINYINT NOT NULL DEFAULT '0' AFTER var_detail;
ALTER TABLE llx_bank_status ADD amount_input DOUBLE(24,2) NULL DEFAULT '0' AFTER amount_income;
ALTER TABLE llx_bank_status ADD amount_sale DOUBLE(24,2) NULL DEFAULT '0' AFTER amount_input;
ALTER TABLE llx_bank_status ADD amount_null DOUBLE(24,2) NULL DEFAULT '0' AFTER amount_sale;
ALTER TABLE llx_bank_status ADD amount_advance DOUBLE(24,2) NULL DEFAULT '0' AFTER amount_null;
ALTER TABLE llx_bank_status ADD amount_transf_input DOUBLE(24,2) NULL DEFAULT '0' AFTER amount_advance;
ALTER TABLE llx_bank_status ADD amount_transf_output DOUBLE(24,2) NULL DEFAULT '0' AFTER amount_transf_input;
ALTER TABLE llx_bank_status ADD amount_spending DOUBLE(24,2) NULL DEFAULT '0' AFTER amount_transf_output;
ALTER TABLE llx_bank_status ADD fk_user_mod INTEGER NOT NULL AFTER fk_user_close;
ALTER TABLE llx_bank_status ADD date_create DATE NOT NULL AFTER fk_user_mod;
ALTER TABLE llx_bank_status ADD date_mod DATE NOT NULL AFTER date_create;