CREATE TABLE llx_subsidiary (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(20) NOT NULL,
  label text NULL,
  subsidiary_number varchar(30) NOT NULL,
  subsidiary_matriz tinyint NULL,
  socialreason text NOT NULL,
  nit varchar(30) NOT NULL,
  activity text NULL,
  address text NULL,
  city varchar(50) NULL,
  phone varchar(12) NULL,
  serie varchar(10) NULL,
  message text NULL,
  activity text NULL,
  nit varchar(30) NOT NULL,
  matriz_name varchar(200) NULL,
  matriz_address varchar(255) NULL,
  matriz_phone integer NOT NULL,
  matriz_city varchar(50) NOT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  date_create date NOT NULL,
  date_mod date NOT NULL,
  tms timestamp NOT NULL,
  status varchar(1) NOT NULL
) ENGINE=InnoDB;
