CREATE TABLE llx_request_cash (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(30) NOT NULL,
  fk_projet integer NOT NULL,
  fk_account integer DEFAULT '0',
  fk_account_from integer DEFAULT'0' NULL,
  fk_user_create integer NOT NULL,
  fk_user_assigned integer DEFAULT '0' NULL,
  fk_user_authorized integer DEFAULT '0' NULL,
  fk_user_approved integer DEFAULT '0' NULL,
  fk_user_mod integer NOT NULL,
  fk_type_cash integer NOT NULL,
  fk_type varchar(6) NULL,
  fk_categorie integer DEFAULT '0' NULL,
  detail text NOT NULL,
  description text NULL,
  document varchar(255) NULL,
  document_discharg varchar(255) NULL,
  amount double(24,2) NOT NULL,
  amount_approved double(24,2) DEFAULT '0' NULL,
  amount_authorized double(24,2) DEFAULT '0.00',
  amount_out double(24,2) DEFAULT '0.00' NULL,
  amount_close double(24,2) DEFAULT '0.00' NULL,
  model_pdf varchar(50) NULL,
  nro_chq varchar(50) NULL,
  date_create date NOT NULL,
  date_approved datetime NULL,
  date_authorized datetime NULL,
  date_delete date DEFAULT NULL,
  tms timestamp,
  status_trans tinyint DEFAULT '0' NOT NULL,
  status tinyint NOT NULL
) ENGINE=InnoDB;
