CREATE TABLE llx_request_cash_deplacement (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer NOT NULL,
	ref varchar(30) NOT NULL,
	fk_parent integer DEFAULT '0' NOT NULL,
	fk_request_cash integer DEFAULT '0' NOT NULL,
	fk_request_cash_dest integer DEFAULT '0' NULL,
	fk_projet_dest integer DEFAULT '0' NULL,
	fk_projet_task_dest integer DEFAULT '0' NULL,
	fk_account_from integer DEFAULT '0' NULL,
	fk_account_dest integer DEFAULT '0' NULL,
	url_id integer DEFAULT '0' NULL,
	fk_bank integer DEFAULT '0' NULL,
	fk_commande_fourn integer DEFAULT NULL,
	fk_facture_fourn integer DEFAULT NULL,
	fk_entrepot integer DEFAULT NULL,
	fk_user_from integer DEFAULT '0' NULL,
	fk_user_to integer DEFAULT 0 NULL,
	fk_type varchar(50) NULL,
	fk_categorie integer DEFAULT '0' NULL,
	fk_soc integer DEFAULT '0' NULL,
	dateo date NULL,
	date_dis date NULL,
	date_app date NULL,
	fk_parent_app integer DEFAULT NULL,
	quant double(18,5) DEFAULT '0' NULL,
	fk_unit integer DEFAULT '0' NULL,
	code_facture varchar(30) NULL,
	code_type_purchase varchar(30) NULL,
	type_operation tinyint DEFAULT '0' NOT NULL,
	nro_chq varchar(50) NULL,
	amount double(24,5) DEFAULT 0 NOT NULL,
	concept varchar(50) NOT NULL,
	detail text NULL,
	nit_company varchar(30) NULL,
	codeqr text NULL,
	fourn_nit varchar(30) DEFAULT NULL,
	fourn_soc varchar(255) DEFAULT NULL,
	fourn_facture varchar(30) DEFAULT NULL,
	fourn_numaut varchar(50) DEFAULT NULL,
	fourn_date date DEFAULT NULL,
	fourn_amount_ttc double DEFAULT NULL,
	fourn_amount double DEFAULT NULL,
	fourn_codecont varchar(20) DEFAULT NULL,
	fourn_reg1 varchar(30) DEFAULT NULL,
	fourn_reg2 varchar(30) DEFAULT NULL,
	fourn_reg3 varchar(30) DEFAULT NULL,
	fourn_reg4 varchar(30) DEFAULT NULL,
	fourn_reg5 varchar(30) DEFAULT NULL,  
	fk_user_create integer NOT NULL,
	fk_user_approved integer DEFAULT '0' NULL,
	date_dest date NULL,
	date_create date NOT NULL,
	tms timestamp,
	status tinyint NOT NULL
) ENGINE=InnoDB;


