ALTER TABLE llx_request_cash ADD UNIQUE KEY uk_request_cash_unique (entity,ref);
ALTER TABLE llx_request_cash ADD document varchar(255) NULL after amount;
ALTER TABLE llx_request_cash ADD document_discharg VARCHAR(255) NULL AFTER document;
ALTER TABLE llx_request_cash ADD amount_out double(24,2) DEFAULT '0' NULL AFTER amount_authorized;
ALTER TABLE llx_request_cash ADD amount_close double(24,2) DEFAULT '0' NULL AFTER amount_out;
ALTER TABLE llx_request_cash ADD amount_approved DOUBLE(24,2) NULL DEFAULT '0' AFTER document_discharg;
ALTER TABLE llx_request_cash ADD model_pdf VARCHAR(50) NULL AFTER amount_close;
ALTER TABLE llx_request_cash ADD fk_type VARCHAR(6) NULL AFTER fk_user_mod;
ALTER TABLE llx_request_cash ADD fk_user_authorized INTEGER NULL DEFAULT '0' AFTER fk_user_create;
ALTER TABLE llx_request_cash ADD fk_user_approved INTEGER NULL DEFAULT '0' AFTER fk_user_authorized;
ALTER TABLE llx_request_cash ADD date_approved DATETIME NULL AFTER date_create;
ALTER TABLE llx_request_cash ADD date_authorized DATETIME NULL AFTER date_approved;
ALTER TABLE llx_request_cash ADD nro_chq VARCHAR(50) NULL AFTER model_pdf;
ALTER TABLE llx_request_cash ADD fk_categorie INTEGER DEFAULT '0' NULL AFTER fk_type;
ALTER TABLE llx_request_cash ADD fk_user_assigned INTEGER NULL DEFAULT '0' AFTER fk_user_create;
ALTER TABLE llx_request_cash ADD description TEXT NULL AFTER detail;
ALTER TABLE llx_request_cash ADD fk_account_from INTEGER NULL DEFAULT '0' AFTER fk_account;
ALTER TABLE llx_request_cash ADD fk_type_cash INTEGER NOT NULL AFTER fk_user_mod;
ALTER TABLE llx_request_cash CHANGE statut status TINYINT NOT NULL ;
ALTER TABLE llx_request_cash ADD status_trans TINYINT NOT NULL DEFAULT '0' AFTER tms;