ALTER TABLE llx_request_cash_deplacement ADD UNIQUE KEY uk_unique (fk_request_cash,fk_deplacement);
ALTER TABLE llx_request_cash_deplacement ADD INDEX idx_code_facture (code_facture);
ALTER TABLE llx_request_cash_deplacement ADD INDEX idx_code_type_purchase (code_type_purchase);

ALTER TABLE llx_request_cash_deplacement ADD fk_parent INTEGER NOT NULL DEFAULT '0' AFTER ref;
ALTER TABLE llx_request_cash_deplacement ADD fk_request_cash_dest integer NULL DEFAULT '0' AFTER fk_request_cash;
ALTER TABLE llx_request_cash_deplacement ADD fk_user_from INTEGER NULL DEFAULT '0' AFTER fk_bank;
ALTER TABLE llx_request_cash_deplacement ADD fk_user_approved INTEGER NULL AFTER fk_user_create;
ALTER TABLE llx_request_cash_deplacement CHANGE url_id url_id INTEGER DEFAULT '0' NULL;
ALTER TABLE llx_request_cash_deplacement CHANGE fk_bank fk_bank INTEGER DEFAULT '0' NULL;
ALTER TABLE llx_request_cash_deplacement ADD fk_projet_dest INTEGER NULL DEFAULT '0' AFTER fk_request_cash_dest;
ALTER TABLE llx_request_cash_deplacement ADD fk_account_dest INTEGER NULL DEFAULT '0' AFTER fk_projet_dest;
ALTER TABLE llx_request_cash_deplacement ADD detail TEXT NULL AFTER concept;
ALTER TABLE llx_request_cash_deplacement ADD fk_account_from INTEGER NULL DEFAULT '0' AFTER fk_projet_dest;
ALTER TABLE llx_request_cash_deplacement ADD date_dest DATE NULL AFTER fk_user_approved;
ALTER TABLE llx_request_cash_deplacement ADD fk_type VARCHAR(50) NULL AFTER fk_user_to;
ALTER TABLE llx_request_cash_deplacement ADD fk_categorie INTEGER NULL DEFAULT '0' AFTER fk_type;
ALTER TABLE llx_request_cash_deplacement ADD dateo DATE NULL AFTER fk_categorie;
ALTER TABLE llx_request_cash_deplacement ADD quant DOUBLE(18,5) NULL DEFAULT '0' AFTER dateo;
ALTER TABLE llx_request_cash_deplacement ADD fk_unit INTEGER NULL DEFAULT '0' AFTER quant;
ALTER TABLE llx_request_cash_deplacement ADD nro_chq VARCHAR(50) NULL AFTER fk_unit;
ALTER TABLE llx_request_cash_deplacement ADD entity INTEGER NOT NULL AFTER rowid;
ALTER TABLE llx_request_cash_deplacement ADD ref VARCHAR(30) NOT NULL AFTER entity;
ALTER TABLE llx_request_cash_deplacement ADD code_facture VARCHAR(30) NULL AFTER fk_unit;
ALTER TABLE llx_request_cash_deplacement ADD fk_projet_task_dest INTEGER NULL AFTER fk_projet_dest;
ALTER TABLE llx_request_cash_deplacement ADD fk_commande_fourn INTEGER NULL AFTER fk_bank;
ALTER TABLE llx_request_cash_deplacement ADD fk_facture_fourn INTEGER NULL AFTER fk_commande_fourn;
ALTER TABLE llx_request_cash_deplacement ADD fk_entrepot INTEGER NULL AFTER fk_facture_fourn;
ALTER TABLE llx_request_cash_deplacement ADD codeqr TEXT NULL AFTER detail;
ALTER TABLE llx_request_cash_deplacement ADD fourn_nit VARCHAR( 30 ) NULL AFTER codeqr;
ALTER TABLE llx_request_cash_deplacement ADD fourn_facture VARCHAR( 30 ) NULL AFTER fourn_nit;
ALTER TABLE llx_request_cash_deplacement ADD fourn_numaut VARCHAR( 50 ) NULL AFTER fourn_facture;
ALTER TABLE llx_request_cash_deplacement ADD fourn_date DATE NULL AFTER fourn_numaut;
ALTER TABLE llx_request_cash_deplacement ADD fourn_amount_ttc DOUBLE NULL AFTER fourn_date;
ALTER TABLE llx_request_cash_deplacement ADD fourn_amount DOUBLE NULL AFTER fourn_amount_ttc;
ALTER TABLE llx_request_cash_deplacement ADD fourn_codecont VARCHAR( 20 ) NULL AFTER fourn_amount;
ALTER TABLE llx_request_cash_deplacement ADD fourn_reg1 VARCHAR( 30 ) NULL AFTER fourn_codecont;
ALTER TABLE llx_request_cash_deplacement ADD fourn_reg2 VARCHAR( 30 ) NULL AFTER fourn_reg1;
ALTER TABLE llx_request_cash_deplacement ADD fourn_reg3 VARCHAR( 30 ) NULL AFTER fourn_reg2;
ALTER TABLE llx_request_cash_deplacement ADD fourn_reg4 VARCHAR( 30 ) NULL AFTER fourn_reg3;
ALTER TABLE llx_request_cash_deplacement ADD fourn_reg5 VARCHAR( 30 ) NULL AFTER fourn_reg4;
ALTER TABLE llx_request_cash_deplacement ADD fk_soc INTEGER DEFAULT '0' NULL AFTER fk_categorie;
ALTER TABLE llx_request_cash_deplacement ADD fourn_soc VARCHAR( 255 ) NULL AFTER fourn_nit;
ALTER TABLE llx_request_cash_deplacement CHANGE statut status TINYINT DEFAULT '0' NOT NULL;
ALTER TABLE llx_request_cash_deplacement ADD code_type_purchase VARCHAR(30) NULL AFTER code_facture;
ALTER TABLE llx_request_cash_deplacement ADD type_operation TINYINT NOT NULL DEFAULT '0' AFTER code_type_purchase;
ALTER TABLE llx_request_cash_deplacement ADD nit_company VARCHAR(30) NULL AFTER detail;
ALTER TABLE llx_request_cash_deplacement ADD date_dis DATE NULL AFTER dateo;
ALTER TABLE llx_request_cash_deplacement ADD date_app DATE NULL AFTER date_dis;
ALTER TABLE llx_request_cash_deplacement ADD fk_parent_app INTEGER NULL AFTER date_app;

ALTER TABLE llx_request_cash_deplacement ADD FOREIGN KEY (code_type_purchase) REFERENCES llx_c_type_purchase(code) ON DELETE RESTRICT ON UPDATE CASCADE;

