CREATE TABLE llx_projet_task_resource (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_projet_task integer NOT NULL DEFAULT '0',
  ref varchar(30) NOT NULL,
  ref_ext varchar(30) NULL,
  date_resource date NOT NULL,
  fk_object integer NOT NULL,
  object varchar(100) NOT NULL,
  fk_objectdet integer NULL,
  objectdet varchar(100) NULL,
  fk_stock_mouvement integer DEFAULT '0' NULL,
  fk_user_create integer NOT NULL DEFAULT '0',
  fk_user_mod integer NOT NULL DEFAULT '0',
  group_resource varchar(2) NOT NULL,
  type_resource varchar(6) NOT NULL,
  code_structure varchar(30) NOT NULL,
  fk_product integer DEFAULT '0',
  fk_product_projet integer NOT NULL,
  fk_product_budget integer DEFAULT '0' NULL,
  fk_facture_fourn integer DEFAULT '0' NULL,
  fk_projet_paiement integer DEFAULT '0' NULL,
  detail varchar(150) DEFAULT NULL,
  fk_unit integer NOT NULL DEFAULT '0',
  quant double DEFAULT '0',
  percent_prod double NOT NULL DEFAULT '100',
  amount_noprod double NOT NULL DEFAULT '0',
  amount double DEFAULT '0',
  rang integer NOT NULL,
  date_create date NOT NULL,
  date_mod date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL DEFAULT '0'
) ENGINE=InnoDB;