CREATE TABLE llx_projet_task_base (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  ref varchar(50) DEFAULT NULL,
  entity integer NOT NULL DEFAULT '1',
  fk_projet_task integer NOT NULL,
  fk_projet integer NOT NULL,
  fk_task_parent integer NOT NULL DEFAULT '0',
  datec datetime DEFAULT NULL,
  tms timestamp,
  dateo datetime DEFAULT NULL,
  datee datetime DEFAULT NULL,
  datev datetime DEFAULT NULL,
  label varchar(255) NOT NULL,
  description text,
  duration_effective double NOT NULL DEFAULT '0',
  planned_workload double NOT NULL DEFAULT '0',
  progress integer DEFAULT '0',
  priority integer DEFAULT '0',
  fk_user_creat integer DEFAULT NULL,
  fk_user_valid integer DEFAULT NULL,
  fk_statut smallint NOT NULL DEFAULT '0',
  note_private text,
  note_public text,
  rang integer DEFAULT '0',
  model_pdf varchar(255) DEFAULT NULL
) ENGINE=InnoDB;
