CREATE TABLE llx_projet_product (
  rowid integer NOT NULL,
  fk_projet integer NOT NULL,
  fk_product integer NOT NULL,
  ref varchar(128) NOT NULL,
  ref_ext varchar(128) DEFAULT NULL,
  datec datetime DEFAULT NULL,
  tms timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_parent integer DEFAULT '0',
  fk_categorie integer NOT NULL,
  label varchar(255) NOT NULL,
  description text,
  fk_country integer DEFAULT NULL,
  price double(24,8) DEFAULT '0.00000000',
  price_ttc double(24,8) DEFAULT '0.00000000',
  price_min double(24,8) DEFAULT '0.00000000',
  price_min_ttc double(24,8) DEFAULT '0.00000000',
  price_base_type varchar(3) DEFAULT 'HT',
  tva_tx double(6,3) DEFAULT NULL,
  recuperableonly integer NOT NULL DEFAULT '0',
  localtax1_tx double(6,3) DEFAULT '0.000',
  localtax1_type varchar(10) NOT NULL DEFAULT '0',
  localtax2_tx double(6,3) DEFAULT '0.000',
  localtax2_type varchar(10) NOT NULL DEFAULT '0',
  fk_user_author integer DEFAULT NULL,
  fk_user_modif integer DEFAULT NULL,
  fk_product_type integer DEFAULT '0',
  pmp double(24,8) NOT NULL DEFAULT '0.00000000',
  finished tinyint DEFAULT NULL,
  fk_unit integer DEFAULT NULL,
  cost_price double(24,8) DEFAULT NULL,
  status tinyint NOT NULL DEFAULT '1'
) ENGINE=InnoDB;