CREATE TABLE llx_projet_paiementdet (
  rowid integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fk_projet_paiement integer NOT NULL DEFAULT '0',
  ref varchar(30) NOT NULL,
  date_paiement date NOT NULL,
  fk_projet_task integer NOT NULL,
  fk_object integer NOT NULL,
  object varchar(100) NOT NULL,
  fk_objectdet integer NOT NULL DEFAULT '0',
  objectdet varchar(100) NOT NULL,
  fk_user_create integer NOT NULL DEFAULT '0',
  fk_user_mod integer NOT NULL DEFAULT '0',
  fk_product integer DEFAULT '0',
  fk_facture_fourn integer DEFAULT '0',
  detail varchar(150) DEFAULT NULL,
  fk_unit integer NOT NULL DEFAULT '0',
  qty_ant double DEFAULT '0',
  qty double DEFAULT '0',
  subprice double NOT NULL,
  price double NOT NULL DEFAULT '0',
  total_ht double DEFAULT '0',
  total_ttc double NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL DEFAULT '0'
) ENGINE=InnoDB;