CREATE TABLE llx_facture_fourn_det_add (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_facture_fourn_det integer NOT NULL,
  fk_object integer NULL,
  object varchar(255) NULL,
  fk_fabrication integer DEFAULT '0' NULL,
  fk_fabricationdet integer DEFAULT '0' NULL,
  fk_projet integer DEFAULT '0' NULL,
  fk_projet_task integer DEFAULT '0' NULL,
  fk_jobs integer DEFAULT '0' NULL,
  fk_jobsdet integer DEFAULT '0' NULL,
  fk_structure integer DEFAULT '0' NULL,
  fk_poa integer DEFAULT '0' NULL,
  partida varchar(10) DEFAULT NULL,
  amount_ice double DEFAULT '0' NULL,
  discount double DEFAULT '0' NULL,
  fk_asset integer DEFAULT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  date_create date NOT NULL,
  date_mod date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL DEFAULT '0'
) ENGINE=InnoDB;
