CREATE TABLE llx_purchase_requestdet (
  rowid integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fk_purchase_request integer NOT NULL,
  ref varchar(30) NOT NULL,
  fk_parent_line integer DEFAULT NULL,
  fk_product integer DEFAULT NULL,
  fk_fabrication integer DEFAULT '0' NULL,
  fk_fabricationdet integer DEFAULT '0' NULL,
  fk_projet integer DEFAULT '0' NULL,
  fk_projet_task integer DEFAULT '0' NULL,
  fk_jobs integer DEFAULT '0' NULL,
  fk_jobsdet integer DEFAULT '0' NULL,
  fk_structure integer DEFAULT '0' NULL,
  fk_poa integer DEFAULT '0' NULL,
  fk_poa_partida_pre_det integer DEFAULT '0' NULL,
  fk_commande_fournisseurdet integer DEFAULT '0' NULL,
  partida varchar(10) DEFAULT NULL,
  label varchar(255) DEFAULT NULL,
  description text,
  qty double DEFAULT NULL,
  fk_unit integer DEFAULT NULL,
  tva_tx double DEFAULT '0' NULL,
  subprice double DEFAULT '0' NULL,
  price double DEFAULT '0' NULL,
  total_ht double DEFAULT '0',
  total_ttc double DEFAULT '0',
  product_type integer DEFAULT '0',
  info_bits integer DEFAULT '0',
  special_code integer DEFAULT '0',
  rang integer DEFAULT '0',
  ref_fourn varchar(30) DEFAULT NULL,
  origin varchar(150) DEFAULT NULL,
  originid integer DEFAULT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL DEFAULT '0'
) ENGINE=InnoDB;