CREATE TABLE llx_facture_fourn_add (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_facture_fourn integer NOT NULL,
  object varchar(255) DEFAULT NULL,
  fk_object integer DEFAULT '0' NULL,
  fk_departament integer DEFAULT NULL,
  fk_projet_task integer DEFAULT NULL,
  code_facture varchar(12) NOT NULL,
  code_type_purchase varchar(12) NOT NULL,
  nit_company varchar(30) NULL,
  nfiscal integer DEFAULT NULL,
  ndui varchar(50) DEFAULT NULL,
  num_autoriz varchar(30) DEFAULT NULL,
  nit varchar(50) DEFAULT NULL,
  razsoc varchar(200) DEFAULT NULL,
  cod_control varchar(30) DEFAULT NULL,
  codqr varchar(255) DEFAULT NULL,
  amountfiscal double DEFAULT '0' NULL,
  amountnofiscal double DEFAULT '0' NULL,
  amount_ice double DEFAULT '0' NULL,
  discount double DEFAULT NULL,
  datec datetime DEFAULT NULL,
  tms timestamp,
  localtax3 double DEFAULT NULL,
  localtax4 double DEFAULT NULL,
  localtax5 double DEFAULT NULL,
  localtax6 double DEFAULT NULL,
  localtax7 double DEFAULT NULL,
  localtax8 double DEFAULT NULL,
  localtax9 double DEFAULT NULL
) ENGINE=InnoDB;

