CREATE TABLE llx_purchase_request (
  rowid integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL DEFAULT '1',
  ref varchar(30) NOT NULL,
  ref_ext varchar(255) DEFAULT NULL,
  ref_int varchar(255) DEFAULT NULL,
  fk_projet integer DEFAULT NULL,
  fk_poa_prev integer DEFAULT '0' NULL,
  fk_departament integer NOT NULL,
  tms timestamp NOT NULL,
  datec datetime DEFAULT NULL,
  date_valid datetime DEFAULT NULL,
  date_cloture datetime DEFAULT NULL,
  fk_user_author integer DEFAULT NULL,
  fk_user_modif integer DEFAULT NULL,
  fk_user_valid integer DEFAULT NULL,
  fk_user_cloture integer DEFAULT NULL,
  note_private text,
  note_public text,
  model_pdf varchar(255) DEFAULT NULL,
  origin varchar(150) DEFAULT NULL,
  originid integer DEFAULT NULL,
  date_delivery datetime DEFAULT NULL,
  date_livraison datetime DEFAULT NULL,
  fk_shipping_method integer DEFAULT NULL,
  import_key varchar(14) DEFAULT NULL,
  extraparams varchar(255) DEFAULT NULL,
  datem date NOT NULL,
  status tinyint NOT NULL DEFAULT '0',
  status_process tinyint NOT NULL DEFAULT '0',
  status_purchase tinyint NOT NULL DEFAULT '0'
) ENGINE=InnoDB;