CREATE TABLE llx_commande_fournisseur_add (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	fk_commande_fournisseur integer NOT NULL,
	object varchar(255) DEFAULT NULL,
	fk_object integer DEFAULT '0' NULL,
	fk_departament integer DEFAULT '0' NULL,
	ref_contrat VARCHAR(40) NULL,
	term INTEGER NULL,
	ref_term TINYINT NULL,
	type VARCHAR(2) NULL,
	advance TINYINT NULL,
	order_proceed TINYINT NULL,
	designation_fiscal TINYINT NULL,
	designation_supervisor TINYINT NULL,
	date_ini date NULL,
	date_fin date NULL,
	date_order_proced date NULL,
	delivery_place text NULL,
	fk_poa_prev integer DEFAULT '0' NULL,
	code_facture varchar(12) NOT NULL,
	code_type_purchase varchar(12) NOT NULL,
	amountfiscal double DEFAULT '0',
	amountnofiscal double DEFAULT '0',
	discount double DEFAULT NULL,
	datec datetime DEFAULT NULL,
	fk_user_create integer NOT NULL,
	fk_user_mod integer NOT NULL,
	date_create date NOT NULL,
	date_mod date NOT NULL,
	tms timestamp,
	status tinyint NOT NULL DEFAULT '0'
) ENGINE=InnoDB;

