CREATE TABLE llx_sol_almacen (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(30) NOT NULL,
  fk_entrepot_from integer DEFAULT '0' NOT NULL,
  fk_entrepot integer NOT NULL,
  fk_fabrication integer NOT NULL DEFAULT '0',
  fk_departament integer DEFAULT '0' NULL,
  fk_projet integer DEFAULT '0' NULL,
  fk_user integer NOT NULL DEFAULT '0',
  date_creation date NOT NULL,
  date_delivery date NOT NULL,
  description text,
  model_pdf varchar(50) NULL,
  fk_user_create integer NOT NULL DEFAULT '0',
  fk_user_mod integer NOT NULL DEFAULT '0',
  fk_user_app integer NULL,
  fk_user_ent integer NULL,
  datea date NULL,
  datee date NULL,
  datem date NOT NULL,
  tms timestamp,
  statut tinyint NOT NULL DEFAULT '0'
) ENGINE=InnoDB;
