CREATE TABLE llx_stock_mouvement_pricemod (
  rowid integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fk_stock_mouvement integer NOT NULL,
  period_year mediumint NOT NULL DEFAULT '0',
  month_year tinyint NOT NULL DEFAULT '1',
  date_closed date NOT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  fk_parent_line integer DEFAULT '0',
  qty double DEFAULT '0',
  price double(24,8) DEFAULT '0',
  balance_peps double DEFAULT '0',
  balance_ueps double DEFAULT '0',
  value_peps double DEFAULT '0',
  value_ueps double DEFAULT '0',
  balance_peps_new double NOT NULL DEFAULT '0',
  balance_ueps_new double NOT NULL DEFAULT '0',
  price_new double NOT NULL DEFAULT '0',
  value_peps_new double NOT NULL DEFAULT '0',
  value_ueps_new double NOT NULL DEFAULT '0',
  datec datetime NOT NULL,
  datem date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL DEFAULT '1'
) ENGINE=InnoDB;