CREATE TABLE llx_stock_mouvement_add (
  rowid integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fk_stock_mouvement integer NOT NULL,
  period_year mediumint NOT NULL,
  month_year tinyint NOT NULL,
  fk_stock_mouvement_doc integer NOT NULL,
  fk_facture integer DEFAULT '0',
  fk_facturedet integer DEFAULT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  fk_parent_line integer DEFAULT '0' NULL,
  qty double DEFAULT '0' NULL,
  balance_peps double DEFAULT '0',
  balance_ueps double DEFAULT '0',
  value_peps double DEFAULT '0',
  value_ueps double DEFAULT '0',
  value_peps_adq double DEFAULT '0',
  value_ueps_adq double DEFAULT '0',
  process_type tinyint DEFAULT '0',
  date_create datetime NOT NULL,
  date_mod date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL DEFAULT '0'
) ENGINE=InnoDB;