CREATE TABLE llx_sol_almacendet (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_almacen integer NOT NULL,
  fk_product integer NOT NULL,
  fk_unit integer NULL,
  fk_fabricationdet integer DEFAULT '0' NULL,
  fk_projet integer DEFAULT 0 NULL,
  fk_projet_task integer DEFAULT 0 NULL,
  fk_jobs integer DEFAULT '0' NULL,
  fk_jobsdet integer DEFAULT '0' NULL,
  fk_structure integer DEFAULT '0' NULL,
  fk_entrepot integer DEFAULT NULL,
  description text NULL,
  qty double(24,8) NOT NULL,
  qty_livree double(24,8) DEFAULT NULL,
  price double(24,8) DEFAULT '0',
  price_peps double(24,8) DEFAULT '0' NULL,
  price_ueps double(24,8) DEFAULT '0' NULL,
  date_shipping date DEFAULT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  date_create date NOT NULL,
  date_mod date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint DEFAULT 0 NOT NULL
) ENGINE=InnoDB;
