CREATE TABLE llx_stock_mouvement_temp (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(30) NOT NULL,
  tms timestamp,
  datem datetime DEFAULT NULL,
  fk_product integer NOT NULL,
  fk_entrepot integer NOT NULL,
  fk_type_mov integer DEFAULT '0',
  value double DEFAULT NULL,
  quant double DEFAULT '0',
  price double(24,8) DEFAULT '0.00000000',
  balance_peps double DEFAULT '0' NULL,
  balance_ueps double DEFAULT '0' NULL,
  price_peps double DEFAULT '0' NULL,
  price_ueps double DEFAULT '0' NULL,
  type_mouvement smallint DEFAULT NULL,
  fk_user_author integer DEFAULT NULL,
  label varchar(255) DEFAULT NULL,
  fk_origin integer DEFAULT NULL,
  origintype varchar(32) DEFAULT NULL,
  inventorycode varchar(128) DEFAULT NULL,
  batch varchar(30) DEFAULT NULL,
  eatby date DEFAULT NULL,
  sellby date DEFAULT NULL,
  statut tinyint DEFAULT '0' NULL
) ENGINE=InnoDB;
