ALTER TABLE llx_budget DROP INDEX uk_budget_ref;
ALTER TABLE llx_budget ADD UNIQUE uk_unique ( entity , ref , version );
ALTER TABLE llx_budget ADD version TINYINT NOT NULL DEFAULT '1' AFTER entity;
ALTER TABLE llx_budget ADD type_structure VARCHAR(30) NOT NULL AFTER entity;
ALTER TABLE llx_budget ADD fk_soc INTEGER NOT NULL DEFAULT '0' AFTER entity;
ALTER TABLE llx_budget ADD INDEX idx_budget_fk_soc (fk_soc);
ALTER TABLE llx_budget ADD fk_projet INTEGER NULL DEFAULT '0' AFTER fk_soc;
ALTER TABLE llx_budget ADD fk_calendar INTEGER NULL DEFAULT '0' AFTER fk_projet;
ALTER TABLE llx_budget ADD fk_country INTEGER NULL AFTER fk_calendar;
ALTER TABLE llx_budget ADD fk_departament INTEGER NULL AFTER fk_country;
ALTER TABLE llx_budget ADD fk_city INTEGER NULL AFTER fk_departament;
ALTER TABLE llx_budget ADD location text NULL AFTER fk_city;
ALTER TABLE llx_budget ADD data_type VARCHAR( 1 ) NOT NULL DEFAULT '0' AFTER fk_city;
ALTER TABLE llx_budget ADD dateo date DEFAULT NULL AFTER tms;
ALTER TABLE llx_budget ADD datee date DEFAULT NULL AFTER dateo;
ALTER TABLE llx_budget ADD ref varchar(30) DEFAULT NULL AFTER datee;
ALTER TABLE llx_budget ADD title varchar(255) DEFAULT NULL AFTER type_structure;
ALTER TABLE llx_budget ADD description text DEFAULT NULL AFTER title;
ALTER TABLE llx_budget ADD fk_region INTEGER NOT NULL DEFAULT '0' AFTER fk_city;
ALTER TABLE llx_budget ADD fk_sector INTEGER NOT NULL DEFAULT '0' AFTER fk_region;
ALTER TABLE llx_budget ADD public INTEGER NOT NULL DEFAULT '0' AFTER fk_user_creat;
ALTER TABLE llx_budget ADD fk_statut INTEGER NOT NULL DEFAULT '0' AFTER public;
ALTER TABLE llx_budget ADD fk_opp_status INTEGER NOT NULL DEFAULT '0' AFTER fk_statut;
ALTER TABLE llx_budget ADD opp_percent DOUBLE(5,2) NOT NULL DEFAULT '0' AFTER fk_opp_status;
ALTER TABLE llx_budget ADD date_close DATETIME NULL AFTER opp_percent;
ALTER TABLE llx_budget ADD fk_user_close INTEGER NOT NULL DEFAULT '0' AFTER date_close;
ALTER TABLE llx_budget ADD note_private text  AFTER fk_user_close;
ALTER TABLE llx_budget ADD note_public text  AFTER note_private;
ALTER TABLE llx_budget ADD opp_amount DOUBLE(24,8) NOT NULL DEFAULT '0' AFTER note_public;
ALTER TABLE llx_budget ADD budget_amount DOUBLE(24,8) NOT NULL DEFAULT '0' AFTER opp_amount;
ALTER TABLE llx_budget ADD model_pdf VARCHAR(255) NULL DEFAULT NULL AFTER budget_amount;

ALTER TABLE llx_budget CHANGE fk_departament fk_departement INTEGER;