CREATE TABLE llx_budget (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL DEFAULT '1',
  fk_soc integer DEFAULT NULL,
  fk_projet integer DEFAULT '0' NULL,
  fk_calendar integer DEFAULT '0' NULL,
  fk_country integer DEFAULT '0' NULL,
  fk_departement integer DEFAULT '0' NULL,
  fk_city integer DEFAULT '0' NULL,
  fk_region integer DEFAULT '0' NOT NULL,
  fk_sector integer DEFAULT '0' NOT NULL,
  data_type varchar(1) DEFAULT '0' NOT NULL,
  location text NULL,
  datec date DEFAULT NULL,
  tms timestamp NOT NULL,
  dateo date DEFAULT NULL,
  datee date DEFAULT NULL,
  ref varchar(50) DEFAULT NULL,
  version varchar(30) NOT NULL DEFAULT '1',
  type_structure varchar(30) NOT NULL,
  title varchar(255) NOT NULL,
  description text,
  fk_user_creat integer NOT NULL,
  public integer DEFAULT NULL,
  fk_statut integer NOT NULL DEFAULT '0',
  fk_opp_status integer DEFAULT NULL,
  opp_percent double(5,2) DEFAULT NULL,
  date_close datetime DEFAULT NULL,
  fk_user_close integer DEFAULT NULL,
  note_private text,
  note_public text,
  opp_amount double(24,8) DEFAULT NULL,
  budget_amount double(24,8) DEFAULT NULL,
  model_pdf varchar(255) DEFAULT NULL
) ENGINE=InnoDB;
