CREATE TABLE llx_product_budget (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_product integer NOT NULL,
  fk_budget integer NOT NULL,
  ref varchar(128) NULL,
  label varchar(255) NOT NULL,
  fk_unit integer NOT NULL,
  code_structure varchar(30) NOT NULL,
  group_structure varchar(2) DEFAULT NULL,
  formula varchar(100) DEFAULT NULL,
  units integer DEFAULT '0' NULL,
  commander tinyint DEFAULT '0' NULL,
  performance double(24,8) DEFAULT '0' NULL,
  price_productive double(24,8) DEFAULT '0' NULL,
  price_improductive double(24,8) DEFAULT '0' NULL,
  active tinyint DEFAULT '1' NULL,
  fk_object integer DEFAULT '0' NULL,
  fk_origin integer DEFAULT '0' NULL,
  percent_origin double(7,3) DEFAULT '0' NULL,
  quant double NOT NULL,
  percent_prod double NOT NULL DEFAULT '100',
  amount_noprod double NOT NULL,
  amount double NOT NULL,

  work_hours time NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  date_create datetime NOT NULL,
  date_mod datetime NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL
) ENGINE=InnoDB;