CREATE TABLE llx_incidents_det (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_incident integer NOT NULL,
  type varchar(30) NOT NULL,
  fk_object integer NOT NULL DEFAULT '0',
  object varchar(100) DEFAULT NULL,
  label varchar(150) NOT NULL,
  fk_unit integer DEFAULT '0' NULL,
  sequen integer NOT NULL,
  value_one double(24,8) DEFAULT '0' NULL,
  value_two double(24,8) DEFAULT '0' NULL,
  value_three double(24,8) DEFAULT '0' NULL,
  value_four double(24,8) DEFAULT '0' NULL,
  value_five double(24,8) DEFAULT '0' NULL,
  value_six double(24,8) DEFAULT '0' NULL,
  value_seven double(24,8) DEFAULT '0' NULL,
  res_one double(24,8) DEFAULT '0' NULL,
  res_two double(24,8) DEFAULT '0' NULL,
  res_three double(24,8) DEFAULT '0' NULL,
  res_four double(24,8) DEFAULT '0' NULL,
  res_five double(24,8) DEFAULT '0' NULL,
  res_six double(24,8) DEFAULT '0' NULL,
  res_seven double(24,8) DEFAULT '0' NULL,
  quantity integer NOT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL DEFAULT '1'
) ENGINE=InnoDB;
