CREATE TABLE llx_budget_task_resource (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_budget_task integer NOT NULL DEFAULT '0',
  ref varchar(128) NOT NULL,
  fk_user_create integer NOT NULL DEFAULT '0',
  fk_user_mod integer NOT NULL DEFAULT '0',
  code_structure varchar(30) NOT NULL,
  fk_product integer NULL DEFAULT '0',
  fk_product_budget integer NOT NULL DEFAULT '0',
  fk_budget_task_comple integer NULL DEFAULT '0',
  detail varchar(255) NULL,
  fk_unit integer NOT NULL DEFAULT '0',
  quant double(24,8) NULL DEFAULT '0',
  percent_prod double(24,8) NOT NULL DEFAULT '100',
  amount_noprod double(24,8) NULL DEFAULT '0',
  amount double(24,8) NULL DEFAULT '0',
  rang integer NOT NULL,
  priority tinyint DEFAULT '0' NOT NULL,
  units double(24,8) DEFAULT '0' NULL,
  commander tinyint DEFAULT '0' NULL,
  performance double(24,8) DEFAULT '0' NULL,
  price_productive double(24,8) DEFAULT '0' NULL,
  price_improductive double(24,8) DEFAULT '0' NULL,
  formula varchar(200) NULL,
  formula_res double NULL,
  formula_quant double NULL,
  formula_factor double NULL,
  formula_prod double NULL,
  date_create date NOT NULL,
  date_mod date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL DEFAULT '0'
) ENGINE=InnoDB;