CREATE TABLE llx_incidents (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(30) NOT NULL,
  label varchar(200) NOT NULL,
  code_parameter varchar(30) NOT NULL,
  fk_region integer NOT NULL,
  day_year mediumint NOT NULL DEFAULT '0',
  day_efective mediumint NOT NULL DEFAULT '0',
  day_efective_month mediumint NULL DEFAULT '0',
  day_journal mediumint NOT NULL DEFAULT '0',
  day_num integer NOT NULL DEFAULT '0',
  salary_min double(24,8) NOT NULL DEFAULT '0.00000000',
  njobs integer NOT NULL DEFAULT '0',
  cost_direct double(24,8) DEFAULT '0' NULL,
  time_duration integer DEFAULT '0' NULL,
  exchange_rate double(10,3) DEFAULT '0' NULL,
  tva_tx double(24,8) DEFAULT '0' NULL,
  ponderation double(24,8) NOT NULL DEFAULT '0.00000000',
  commission double(24,8) DEFAULT '0' NULL,
  incident double(7,3) NOT NULL,
  active tinyint NOT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL
) ENGINE=InnoDB;
