CREATE TABLE llx_v_dosing_history (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_dosing integer NOT NULL,
  entity integer NOT NULL,
  fk_subsidiaryid integer NOT NULL,
  series varchar(4) NOT NULL,
  num_ini integer NOT NULL,
  num_fin integer NOT NULL DEFAULT '0',
  num_ult integer NOT NULL DEFAULT '0',
  num_aprob varchar(20) DEFAULT NULL,
  type tinyint NOT NULL,
  active tinyint DEFAULT NULL,
  date_val date DEFAULT NULL,
  num_autoriz varchar(15) DEFAULT NULL,
  cod_control varchar(15) DEFAULT NULL,
  lote tinyint NOT NULL,
  chave varchar(254) NOT NULL,
  descrip text,
  activity text,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL
) ENGINE=InnoDB;