CREATE TABLE llx_v_fiscal (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  nfiscal varchar(50) NOT NULL,
  serie varchar(30) NOT NULL,
  fk_dosing integer DEFAULT 0 NOT NULL,
  fk_facture integer DEFAULT 0 NOT NULL,
  fk_cliepro integer NOT NULL,
  nit varchar(50) NOT NULL,
  razsoc varchar(200) NULL,
  date_exp date NOT NULL,
  type_op varchar(30) NOT NULL,
  num_autoriz varchar(15) DEFAULT NULL,
  cod_control varchar(20) DEFAULT NULL,
  remise double(12,4) DEFAULT NULL,
  baseimp1 double(12,4) DEFAULT 0 NULL,
  baseimp2 double(12,4) DEFAULT 0 NULL,
  baseimp3 double(12,4) DEFAULT 0 NULL,
  baseimp4 double(12,4) DEFAULT 0 NULL,
  baseimp5 double(12,4) DEFAULT 0 NULL,
  aliqimp1 double(12,4) DEFAULT 0 NULL,
  aliqimp2 double(12,4) DEFAULT 0 NULL,
  aliqimp3 double(12,4) DEFAULT 0 NULL,
  aliqimp4 double(12,4) DEFAULT 0 NULL,
  aliqimp5 double(12,4) DEFAULT 0 NULL,
  valimp1 double(12,4) DEFAULT 0 NULL,
  valimp2 double(12,4) DEFAULT 0 NULL,
  valimp3 double(12,4) DEFAULT 0 NULL,
  valimp4 double(12,4) DEFAULT 0 NULL,
  valimp5 double(12,4) DEFAULT 0 NULL,
  valret1 double(12,4) DEFAULT 0 NULL,
  valret2 double(12,4) DEFAULT 0 NULL,
  valret3 double(12,4) DEFAULT 0 NULL,
  valret4 double(12,4) DEFAULT 0 NULL,
  valret5 double(12,4) DEFAULT 0 NULL,
  amount_payment double(12,4) DEFAULT 0 NULL,
  amount_balance double(12,4) DEFAULT 0 NULL,
  date_create datetime NOT NULL,
  date_mod date NOT NULL,
  tms timestamp NOT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NUll,
  statut_print tinyint NULL,
  status tinyint NOT NULL
) ENGINE=InnoDB;
