CREATE TABLE llx_v_dosing (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  fk_subsidiaryid integer NOT NULL,
  series varchar(4) NOT NULL,
  num_ini integer NOT NULL,
  num_fin integer NOT NULL,
  num_ult integer DEFAULT 0 NOT NULL,
  num_aprob varchar(20) DEFAULT NULL,
  type tinyint NOT NULL,
  active tinyint DEFAULT NULL,
  date_val date DEFAULT NULL,
  num_autoriz varchar(15) DEFAULT NULL,
  cod_control varchar(15) DEFAULT NULL,
  lote tinyint NOT NULL,
  chave varchar(254) NOT NULL,
  descrip text NULL,
  activity text NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  date_create date NOT NULL,
  date_mod date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL
) ENGINE=InnoDB;
