CREATE TABLE llx_p_salary_history (
rowid integer AUTO_INCREMENT PRIMARY KEY,
entity integer NOT NULL,
ref varchar(30) NOT NULL,
period_year mediumint NOT NULL,
fk_salary_present integer NOT NULL,
fk_proces integer NOT NULL,
fk_type_fol integer NOT NULL,
fk_concept integer NOT NULL,
fk_period integer NOT NULL,
fk_user integer NOT NULL,
fk_cc smallint NOT NULL,
sequen integer DEFAULT '0' NOT NULL,
type smallint NOT NULL,
cuota smallint NOT NULL,
semana smallint NOT NULL,
amount_inf double( 20, 2 ) NOT NULL,
amount double( 24, 5) NOT NULL,
hours_info smallint NOT NULL,
hours smallint NOT NULL,
date_reg date NOT NULL,
date_create date NOT NULL,
date_mod date NOT NULL,
fk_user_create integer NOT NULL,
fk_user_mod integer NOT NULL,
fk_account integer NULL DEFAULT '0',
payment_state tinyint NULL DEFAULT '0',
tms timestamp NOT NULL,
state smallint NOT NULL
) ENGINE = InnoDB;

