CREATE TABLE llx_mant_programming (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  fk_asset integer NOT NULL,
  fk_equipment integer NOT NULL,
  fk_soc integer DEFAULT '0' NULL,
  fk_member integer DEFAULT '0' NULL,
  internal smallint NULL,
  speciality varchar(30) NULL,
  typemant varchar(30) NOT NULL,
  frequency varchar(30) NOT NULL,
  detail_value varchar(200) NOT NULL,
  description text,
  date_ini date DEFAULT NULL,
  date_last date DEFAULT NULL,
  date_next date DEFAULT NULL,
  date_create datetime NOT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  active tinyint NOT NULL DEFAULT '0',
  tms timestamp NOT NULL,
  statut tinyint NOT NULL
) ENGINE=InnoDB;
