CREATE TABLE llx_m_jobs (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(15) NOT NULL,
  date_create datetime NOT NULL,
  fk_work_request integer DEFAULT '0' NOT NULL,
  fk_soc integer NULL,
  fk_member integer NULL,
  fk_charge integer NULL,
  fk_departament integer NULL,
  fk_equipment integer NULL,
  fk_property integer NULL,
  fk_location integer NULL,
  fk_type_repair integer DEFAULT '0' NOT NULL,
  email varchar(200) NOT NULL,
  internal smallint NULL,  
  speciality varchar(30) NULL,
  detail_problem text NULL,
  address_ip varchar(39) NOT NULL,
  fk_departament_assign integer DEFAULT '0' NULL,
  fk_user_assign integer NULL,
  date_assign datetime NULL,
  speciality_assign varchar(30) NULL,
  description_assign text NULL,
  description_prog text NULL,
  date_ini_prog datetime DEFAULT NULL,
  date_fin_prog datetime DEFAULT NULL,
  speciality_prog varchar(30) NULL,
  fk_equipment_prog integer NULL,
  fk_property_prog integer NULL,
  fk_location_prog integer NULL,
  typemant_prog varchar(30) NULL,
  fk_user_prog integer NULL,

  date_ini datetime DEFAULT NULL,
  date_fin datetime DEFAULT NULL,
  speciality_job varchar(30) NULL,
  typemant varchar(30) NULL,
  description_job TEXT NULL,
  group_task tinyint DEFAULT '0' NULL,
  task tinyint DEFAULT '1' NULL,
  image_ini varchar(200) NULL,
  image_fin varchar(200) NULL,

  tokenreg varchar(255) NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint DEFAULT NULL,
  description_confirm text NULL,
  statut_job tinyint NULL DEFAULT '0'
) ENGINE=InnoDB;
