CREATE TABLE llx_m_equipment (
  rowid integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(30) NOT NULL,
  ref_ext varchar(30) DEFAULT NULL,
  label varchar(255) NOT NULL,
  metered tinyint NOT NULL DEFAULT '0',
  accountant double NOT NULL DEFAULT '0',
  accountant_last double NOT NULL DEFAULT '0',
  accountant_mant double NOT NULL DEFAULT '0',
  accountant_mante double NOT NULL DEFAULT '0',
  fk_unit integer NOT NULL,
  margin integer NOT NULL DEFAULT '0',
  trademark varchar(150) DEFAULT NULL,
  model varchar(150) DEFAULT NULL,
  anio year(4) DEFAULT NULL,
  fk_location integer DEFAULT NULL,
  fk_asset integer DEFAULT '0' NULL,
  fk_group integer DEFAULT '0' NULL,
  hour_cost double DEFAULT '0' NULL,
  fk_equipment_program integer NOT NULL DEFAULT '0',
  fk_user_create integer NOT NULL DEFAULT '0',
  fk_user_mod integer NOT NULL DEFAULT '0',
  datec date DEFAULT NULL,
  datem date DEFAULT NULL,
  tms timestamp NOT NULL,
  active tinyint NOT NULL DEFAULT '1',
  status tinyint NOT NULL
) ENGINE=InnoDB;