CREATE TABLE llx_m_work_request (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(15) NOT NULL,
  date_create datetime NOT NULL,
  fk_member integer DEFAULT NULL,
  fk_departament integer DEFAULT NULL,
  fk_equipment integer DEFAULT NULL,
  fk_property integer DEFAULT NULL,
  fk_location integer DEFAULT NULL,
  fk_soc integer DEFAULT NULL,
  fk_type_repair integer DEFAULT NULL,
  email varchar(200) NOT NULL,
  internal smallint DEFAULT NULL,
  detail_problem text,
  address_ip varchar(39) NOT NULL,
  fk_user_assign integer DEFAULT NULL,
  date_assign datetime DEFAULT NULL,
  speciality varchar(30) DEFAULT NULL,
  tokenreg varchar(255) DEFAULT NULL,
  description_prog TEXT DEFAULT NULL,
  date_ini_prog datetime DEFAULT NULL,
  date_fin_prog datetime DEFAULT NULL,
  speciality_prog VARCHAR(30) DEFAULT NULL,
  fk_equipment_prog integer DEFAULT NULL,
  fk_property_prog integer DEFAULT NULL,
  fk_location_prog integer DEFAULT NULL,
  typemant_prog varchar(30) DEFAULT NULL,
  fk_user_prog integer DEFAULT NULL,
  image_ini varchar(200) DEFAULT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  tms timestamp,
  status tinyint DEFAULT NULL,
  description_confirm text,
  statut_job tinyint DEFAULT NULL
) ENGINE=InnoDB;
