CREATE TABLE llx_poa_prev (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  gestion smallint NOT NULL,
  fk_pac integer NOT NULL,
  fk_area integer NOT NULL,
  fk_poa_activity integer DEFAULT '0' NULL,
  origin varchar(150) NULL,
  originid integer DEFAULT '0' NULL,
  code_requirement varchar(30) NOT NULL,
  label varchar(255) NOT NULL,
  pseudonym varchar(50) NULL,
  nro_preventive integer NOT NULL,
  date_preventive date NOT NULL,
  amount double NOT NULL DEFAULT '0',
  priority tinyint NULL DEFAULT '0',
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  tms timestamp NOT NULL,
  statut tinyint NOT NULL DEFAULT '0',
  active tinyint NOT NULL DEFAULT '1'
) ENGINE=InnoDB;
