CREATE TABLE llx_poa_process (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  gestion smallint NOT NULL,
  ref integer NOT NULL,
  fk_area integer NOT NULL,
  fk_poa_prev integer NOT NULL,
  date_process date DEFAULT NULL,
  amount double DEFAULT NULL,
  fk_type_adj integer DEFAULT NULL,
  fk_type_con integer DEFAULT NULL,
  term tinyint DEFAULT NULL,
  label varchar(255) DEFAULT NULL,
  justification TEXT NULL,
  fk_poa_pac integer DEFAULT NULL,
  ref_pac varchar(255) DEFAULT NULL,
  cuce varchar(30) DEFAULT NULL,
  code_process varchar(30) DEFAULT NULL,
  doc_precio_referencial tinyint DEFAULT NULL,
  doc_certif_presupuestaria tinyint DEFAULT NULL,
  doc_especific_tecnica tinyint DEFAULT NULL,
  doc_modelo_contrato tinyint DEFAULT NULL,
  doc_informe_lega tinyint DEFAULT NULL,
  doc_pac tinyint DEFAULT NULL,
  doc_prop tinyint DEFAULT NULL,
  fk_soc integer NULL,
  metodo_sel_anpe tinyint DEFAULT NULL,
  metodo_sel_lpni tinyint DEFAULT NULL,
  metodo_sel_cae tinyint DEFAULT NULL,
  condicion_adicional_anpe tinyint DEFAULT NULL,
  condicion_adicional_lpni tinyint DEFAULT NULL,
  date_create date NOT NULL,
  fk_user_create integer NOT NULL,
  tms timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  statut tinyint NOT NULL DEFAULT '0'
) ENGINE=InnoDB;
