CREATE TABLE llx_poa_poa (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer NOT NULL,
	gestion smallint NOT NULL,
	fk_structure integer NOT NULL,
	ref varchar(30) DEFAULT NULL,
	sigla varchar(30) DEFAULT NULL,
	label varchar(255) NOT NULL,
	pseudonym varchar(255) DEFAULT NULL,
	partida varchar(10) NOT NULL,
	amount double DEFAULT '0',
	classification varchar(255) DEFAULT NULL,
	source_verification varchar(255) DEFAULT NULL,
	unit varchar(255) DEFAULT NULL,
	responsible_one varchar(150) DEFAULT NULL,
	responsible_two varchar(150) DEFAULT NULL,
	responsible varchar(150) DEFAULT NULL,
	m_jan double DEFAULT '0',
	m_feb double DEFAULT '0',
	m_mar double DEFAULT '0',
	m_apr double DEFAULT '0',
	m_may double DEFAULT '0',
	m_jun double DEFAULT '0',
	m_jul double DEFAULT '0',
	m_aug double DEFAULT '0',
	m_sep double DEFAULT '0',
	m_oct double DEFAULT '0',
	m_nov double DEFAULT '0',
	m_dec double DEFAULT '0',
	p_jan double DEFAULT '0',
	p_feb double DEFAULT '0',
	p_mar double DEFAULT '0',
	p_apr double DEFAULT '0',
	p_may double DEFAULT '0',
	p_jun double DEFAULT '0',
	p_jul double DEFAULT '0',
	p_aug double DEFAULT '0',
	p_sep double DEFAULT '0',
	p_oct double DEFAULT '0',
	p_nov double DEFAULT '0',
	p_dec double DEFAULT '0',
	fk_area integer DEFAULT NULL,
	weighting double DEFAULT '0',
	fk_poa_reformulated integer NULL DEFAULT '0',
	version tinyint NOT NULL DEFAULT '0',
	fk_user_create integer NOT NULL,
	fk_user_mod integer NOT NULL,
	datec date NOT NULL,
	datem date NOT NULL,
	tms timestamp NOT NULL,
	statut tinyint NOT NULL DEFAULT '0',
	statut_ref tinyint NOT NULL DEFAULT '0'
) ENGINE=InnoDB;
