CREATE TABLE llx_c_poa_actors (
rowid INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY ,
entity INT NOT NULL ,
code VARCHAR(30) NOT NULL ,
label VARCHAR(200) NOT NULL ,
active TINYINT NOT NULL
) ENGINE = InnoDB;
