CREATE TABLE llx_contab_vision (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(3) NOT NULL,
  fk_parent integer DEFAULT '0' NULL,
  sequence integer NOT NULL,
  account varchar(20) NOT NULL,
  account_sup varchar(20) NULL,
  detail_managment varchar(100) NOT NULL,
  cta_normal varchar(1) NOT NULL,
  cta_column tinyint NOT NULL DEFAULT '0',
  cta_class tinyint NOT NULL,
  cta_identifier varchar(15) NULL,
  cta_operation tinyint NULL,
  cta_balances tinyint NOT NULL,
  cta_totalvis tinyint NOT NULL DEFAULT '0',
  name_vision varchar(80) NOT NULL,
  line varchar(3) NOT NULL,
  fk_accountini integer NULL,
  fk_accountfin integer NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL
) ENGINE=InnoDB;
