CREATE TABLE llx_contab_seat (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer NOT NULL,
  ref varchar(30) NOT NULL,
  ref_ext varchar(50) NULL,
  date_seat date NOT NULL,
  lote varchar(7) NOT NULL,
  sblote varchar(7) NOT NULL,
  doc varchar(7) NOT NULL,
  currency tinyint NOT NULL,
  type_seat tinyint NOT NULL,
  type_numeric varchar(2) NOT NULL,
  sequential varchar(10) NOT NULL,
  seat_month varchar(2) NOT NULL,
  seat_year mediumint NOT NULL,
  document_backing varchar(50) NULL,
  beneficiary varchar(140) NULL,
  spending tinyint NULL,
  resource tinyint NULL,
  accountant tinyint NULL,
  codtr varchar(2) NULL,
  codtrone varchar(2) NULL,
  cbter varchar(1) NULL,
  cbttipo varchar(2) NULL,
  debit_total double(20,5) DEFAULT '0.00000',
  credit_total double(20,5) DEFAULT '0.00000',
  history varchar(240) DEFAULT NULL,
  manual tinyint NOT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint NOT NULL
) ENGINE=InnoDB;
