CREATE TABLE llx_contab_seat_det (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_contab_seat integer NOT NULL,
  debit_account varchar(20) NULL,
  debit_detail varchar(40) NULL,
  credit_account varchar(20) NULL,
  credit_detail varchar(40) NULL,
  fk_parent_auxd integer DEFAULT NULL,
  ref_ext_auxd varchar(30) NULL,
  fk_parent_auxc integer NULL,
  ref_ext_auxc varchar(30) NULL,
  codtr varchar(3) NULL,
  codtr1 varchar(3) NULL,
  gareco varchar(1) NULL,
  oec varchar(3) NULL,
  fuefin varchar(2) NULL,
  otherfin varchar(3) NULL,
  dcd tinyint NULL,
  dcc tinyint NULL,
  amount double(20,5) NOT NULL,
  history varchar(240) NULL,
  sequence varchar(10) NOT NULL,
  fk_standard_seat integer NOT NULL,
  type_seat tinyint NOT NULL,
  routines varchar(10) NOT NULL,
  value02 double(20,5) NULL,
  value03 double(20,5) NULL,
  value04 double(20,5) NULL,
  date_rate date NOT NULL,
  rate double(8,4) NOT NULL,
  fk_user_create integer NOT NULL,
  fk_user_mod integer NOT NULL,
  datec date NOT NULL,
  datem date NOT NULL,
  tms timestamp NOT NULL,
  status tinyint DEFAULT '0' NOT NULL
) ENGINE=InnoDB;
